#!/usr/bin/python -u

from gobject import MainLoop
from dbus.mainloop.glib import DBusGMainLoop

from foo.connection_manager import FooConnectionManager

DBusGMainLoop(set_as_default=True)
FooConnectionManager()
MainLoop().run()
